syntax = "proto3";

package enlangmemo.sync.v1;

import "buf/validate/validate.proto";
import "enlangmemo/sync/v1/entities.proto";

message PullRequest {
  string session_id = 1 [(buf.validate.field).string.len = 32];

  // 当前请求的 batch 序号，从 1 开始
  // 服务端校验 batch_seq == SyncLock.expected_batch_seq
  int32 batch_seq = 2 [(buf.validate.field).int32.gte = 1];
}

message PullResponse {
  // 当前返回的 batch 序号，等于 request.batch_seq
  int32 batch_seq = 1;

  // 本 batch 对应的服务端 usn
  // 一个 batch 包含一个 usn 下的全部变更
  int64 usn = 2 [(buf.validate.field).int64.gte = 0];

  // 这批数据的全部变更
  repeated SyncChange changes = 3;

  // 是否为本轮 Pull 的最后一个 batch
  bool last_batch = 4;
}
